name: sideloader
buildscript: scripts/deploy_sideloader
postinstall: scripts/postinstall.sh
pip:
 - gunicorn
 - django
dependencies:
 - nginx
 - libpq-dev
 - postgresql
 - redis-server
 - python-yaml
