language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
before_script:
  - git config --global user.email "tester@example.com"
  - git config --global user.name "Testy Testerson"
  - cp config.yaml.example config.yaml
  - gem install fpm
  - psql -c 'create database sideloader;' -U postgres
  - python manage.py migrate
script:
  - py.test sideloader/ tests/
